import type { RepositoryAnalysis, GeneratedFile } from "../types.js";

interface SkillTemplate {
  filename: string;
  condition: (analysis: RepositoryAnalysis) => boolean;
  render: (analysis: RepositoryAnalysis) => string;
}

const BASE_SKILLS: SkillTemplate[] = [
  {
    filename: "debugging.md",
    condition: () => true,
    render: (a) => skillContent("Debugging", a, [
      "## When to Use",
      "When tracking down bugs or unexpected behavior in this codebase.",
      "",
      "## Repo-Specific Context",
      `- Primary language: ${a.primaryLanguage}`,
      `- Test framework: ${a.testFrameworks.join(", ") || "None detected"}`,
      `- Entry points: ${a.architecture.entryPoints.join(", ")}`,
      "",
      "## Steps",
      "1. Reproduce the issue with a minimal test case",
      "2. Check the most frequently changed files first (see CRITICAL_PATHS.md)",
      "3. Use the test framework to write a failing test",
      "4. Fix and verify",
    ]),
  },
  {
    filename: "testing.md",
    condition: () => true,
    render: (a) => skillContent("Testing", a, [
      "## When to Use",
      "When writing or updating tests.",
      "",
      "## Repo-Specific Context",
      `- Test structure: ${a.architecture.testStructure}`,
      `- Test frameworks: ${a.testFrameworks.join(", ") || "None detected"}`,
      `- Test coverage level: ${a.testCoverage}`,
      "",
      "## Steps",
      "1. Follow existing test structure and naming conventions",
      `2. Place tests ${a.architecture.testStructure === "colocated" ? "next to source files" : "in the tests/ directory"}`,
      "3. Write both happy path and edge case tests",
      "4. Run the full test suite before committing",
    ]),
  },
  {
    filename: "pr-workflow.md",
    condition: () => true,
    render: (a) => {
      const commitConv = a.conventions.find((c) => c.type === "commit");
      return skillContent("PR Workflow", a, [
        "## When to Use",
        "When creating or reviewing pull requests.",
        "",
        "## Repo-Specific Context",
        `- Default branch: ${a.defaultBranch}`,
        `- Commit style: ${commitConv?.description ?? "No convention detected"}`,
        `- CI: ${a.ciSystems.join(", ") || "None"}`,
        "",
        "## Steps",
        "1. Create a feature branch from the default branch",
        `2. Follow commit convention: ${commitConv?.pattern ?? "free-form"}`,
        "3. Ensure tests pass locally before pushing",
        "4. Create PR with clear description",
      ]);
    },
  },
  {
    filename: "code-review.md",
    condition: () => true,
    render: (a) => skillContent("Code Review", a, [
      "## When to Use",
      "When reviewing code changes.",
      "",
      "## Repo-Specific Context",
      `- Architecture: ${a.architecture.style}`,
      `- Layers: ${a.architecture.layers.join(", ") || "flat structure"}`,
      "",
      "## Checklist",
      "- [ ] Follows project conventions",
      "- [ ] Has appropriate test coverage",
      "- [ ] No security concerns",
      "- [ ] Performance impact considered",
      "- [ ] Documentation updated if needed",
    ]),
  },
  {
    filename: "refactoring.md",
    condition: () => true,
    render: (a) => skillContent("Refactoring", a, [
      "## When to Use",
      "When improving code structure without changing behavior.",
      "",
      "## Repo-Specific Context",
      `- Architecture: ${a.architecture.style}`,
      `- Key modules: ${a.architecture.keyModules.slice(0, 5).join(", ")}`,
      "",
      "## Steps",
      "1. Write tests first to lock in current behavior",
      "2. Make small, incremental changes",
      "3. Run tests after each change",
      "4. Use critical paths list to prioritize high-impact areas",
    ]),
  },
  {
    filename: "documentation.md",
    condition: () => true,
    render: (a) => skillContent("Documentation", a, [
      "## When to Use",
      "When updating or adding documentation.",
      "",
      "## Repo-Specific Context",
      `- Documentation coverage: ${a.documentationCoverage}`,
      "",
      "## Steps",
      "1. Check existing docs in .claude/ directory",
      "2. Follow markdown formatting conventions",
      "3. Include code examples from the actual codebase",
      "4. Run `npx claude-onboard status` to verify doc health",
    ]),
  },
];

function skillContent(
  name: string,
  analysis: RepositoryAnalysis,
  body: string[],
): string {
  return [
    `# ${name} — ${analysis.repoName}`,
    "",
    ...body,
    "",
    "---",
    `*Generated by claude-onboard for ${analysis.repoName}*`,
    "",
  ].join("\n");
}

function makeFrameworkSkill(
  framework: string,
  filename: string,
  depCheck: string,
  tips: string[],
): SkillTemplate {
  return {
    filename,
    condition: (a) => a.frameworks.includes(framework),
    render: (a) =>
      skillContent(framework, a, [
        "## When to Use",
        `When working with ${framework}-specific code.`,
        "",
        "## Repo-Specific Context",
        ...tips,
        "",
        "## Common Gotchas",
        `- Check ${framework} documentation for version-specific behavior`,
        `- Review existing ${framework} patterns in this repo before adding new ones`,
      ]),
  };
}

const FRAMEWORK_SKILLS: SkillTemplate[] = [
  makeFrameworkSkill("Next.js", "nextjs.md", "next", [
    "- Check for App Router vs Pages Router usage",
    "- Review middleware and API routes",
  ]),
  makeFrameworkSkill("React", "react.md", "react", [
    "- Follow existing component patterns",
    "- Check for state management patterns (Redux, Context, Zustand)",
  ]),
  makeFrameworkSkill("Express", "express.md", "express", [
    "- Follow existing middleware patterns",
    "- Check route organization",
  ]),
  makeFrameworkSkill("NestJS", "nestjs.md", "@nestjs/core", [
    "- Follow module/controller/service pattern",
    "- Use decorators consistently",
  ]),
  makeFrameworkSkill("Django", "django.md", "django", [
    "- Follow app structure conventions",
    "- Check URL patterns and views",
  ]),
  makeFrameworkSkill("FastAPI", "fastapi.md", "fastapi", [
    "- Follow existing router patterns",
    "- Use Pydantic models for validation",
  ]),
];

export class SkillBuilder {
  constructor(
    private readonly repoPath: string,
    private readonly analysis: RepositoryAnalysis,
  ) {}

  async buildAll(): Promise<GeneratedFile[]> {
    const allTemplates = [...BASE_SKILLS, ...FRAMEWORK_SKILLS];
    const files: GeneratedFile[] = [];

    for (const template of allTemplates) {
      if (template.condition(this.analysis)) {
        const content = template.render(this.analysis);
        files.push({
          path: `.claude/skills/${template.filename}`,
          content,
          action: "created",
        });
      }
    }

    return files;
  }
}
