import type { RepositoryAnalysis, HumanAnswers } from "../types.js";
import type { ModuleInfo, KeyType, CodePatternInsight, TodoComment, BuildCommand } from "../analyzers/source.js";

const DISCLAIMER =
  "<!-- Auto-generated by claude-onboard. Do not edit between auto markers. -->";
export const AUTO_START = "<!-- onboarder:auto-start -->";
export const AUTO_END = "<!-- onboarder:auto-end -->";

function timestamp(): string {
  return new Date().toISOString();
}

function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const k = key(item);
    const existing = map.get(k);
    if (existing) {
      existing.push(item);
    } else {
      map.set(k, [item]);
    }
  }
  return map;
}

// ── Main CLAUDE.md (inside .claude/) ────────────────────────────────────────
// This is THE file. Everything Claude needs in one place.

export function renderClaudeMd(analysis: RepositoryAnalysis, humanAnswers?: HumanAnswers): string {
  const sa = analysis.sourceAnalysis;
  const lines: string[] = [
    DISCLAIMER,
    `# ${analysis.repoName}`,
    "",
    AUTO_START,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // ── Project identity ──
  const desc = humanAnswers?.projectDescription ?? sa?.projectDescription;
  if (desc) {
    lines.push(desc, "");
  } else {
    lines.push(
      `${analysis.repoName} is a **${analysis.primaryLanguage}** ${analysis.architecture.style}.`,
      "",
    );
  }

  if (sa?.packageStructure) {
    lines.push(`Root package: \`${sa.packageStructure}\``, "");
  }

  // ── Quick commands ──
  const hasBuildCmds = (sa && sa.buildCommands.length > 0) || (humanAnswers?.buildCommands && humanAnswers.buildCommands.length > 0);
  if (hasBuildCmds) {
    lines.push("## Commands", "");
    lines.push("```bash");
    const seen = new Set<string>();
    if (sa) {
      for (const cmd of sa.buildCommands) {
        if (seen.has(cmd.name)) continue;
        seen.add(cmd.name);
        const comment = cmd.source !== cmd.command ? `  # ${cmd.source}` : "";
        lines.push(`${cmd.command}${comment}`);
      }
    }
    if (humanAnswers?.buildCommands) {
      for (const cmd of humanAnswers.buildCommands) {
        if (!seen.has(cmd)) {
          lines.push(`${cmd}  # provided by developer`);
        }
      }
    }
    lines.push("```");
    lines.push("");
  }

  // ── Tech stack (grouped deps — only what's non-obvious) ──
  const depGroups = sa ? groupBy(sa.dependencies, (d) => d.group) : new Map<string, import("../analyzers/source.js").DependencyInfo[]>();
  if (depGroups.size > 0) {
    lines.push("## Tech Stack", "");
    for (const [group, deps] of depGroups) {
      if (group === "other" || group === "code-gen" || group === "logging") continue;
      const names = deps
        .map((d: import("../analyzers/source.js").DependencyInfo) => d.name.split(":").pop()!)
        .slice(0, 5)
        .join(", ");
      lines.push(
        `- **${group}**: ${names}${deps.length > 5 ? ` (+${deps.length - 5} more)` : ""}`,
      );
    }
    lines.push("");
  }

  // ── Architecture (concise — just the rules, not listings) ──
  lines.push("## Architecture", "");
  lines.push(`**Style**: ${analysis.architecture.style}`);
  if (analysis.architecture.layers.length > 0) {
    lines.push(
      `**Layers**: ${analysis.architecture.layers.join(" → ")}`,
    );
  }

  // Module map — only meaningful directories, not package hierarchy noise
  if (sa && sa.modules.length > 0) {
    lines.push("");
    lines.push("**Key modules**:");
    const seen = new Set<string>();
    const meaningful = flattenModules(sa.modules)
      .filter((m) => m.description && !m.description.endsWith("files"))
      .sort((a, b) => b.changeCount - a.changeCount)
      .filter((m) => {
        if (seen.has(m.path)) return false;
        seen.add(m.path);
        return true;
      })
      .slice(0, 12);
    for (const mod of meaningful) {
      lines.push(`- \`${mod.path}/\` — ${mod.description} (${mod.fileCount} files)`);
    }
  }
  lines.push("");

  // ── Code Patterns & Idioms (this is the gold — things Claude can't grep for) ──
  if (sa && sa.codePatterns.length > 0) {
    lines.push("## Code Patterns", "");
    lines.push("Follow these patterns when writing new code:", "");
    for (const p of sa.codePatterns) {
      lines.push(`### ${p.name}`, "");
      lines.push(p.description, "");
    }
  }

  // ── Conventions (merged — no separate file needed) ──
  if (analysis.conventions.length > 0) {
    lines.push("## Conventions", "");
    for (const c of analysis.conventions) {
      lines.push(`- **${c.type}**: ${c.description}`);
      if (c.examples.length > 0) {
        lines.push(`  - Example: \`${c.examples[0]}\``);
      }
    }

    // Commit patterns from deeper analysis
    if (sa?.commitPatterns) {
      const cp = sa.commitPatterns;
      if (cp.branchPattern) {
        lines.push(`- **branches**: ${cp.branchPattern}`);
      }
      if (cp.mergeStrategy !== "unknown") {
        lines.push(`- **merge strategy**: ${cp.mergeStrategy}`);
      }
    }
    lines.push("");
  }

  // ── Service map (microservices) ──
  if (sa && sa.serviceMap.length > 0) {
    lines.push("## Services", "");
    for (const svc of sa.serviceMap) {
      const port = svc.port ? `:${svc.port}` : "";
      const deps = svc.dependsOn.length > 0 ? ` → depends on: ${svc.dependsOn.join(", ")}` : "";
      lines.push(`- **${svc.name}**${port}${deps}`);
    }
    lines.push("");
  }

  // ── Team rules (code-review.rules, .cursor/rules) ──
  if (sa && sa.teamRules.length > 0) {
    lines.push("## Team Rules & Conventions", "");
    lines.push("These rules were found in the repo and should be followed:", "");
    for (const rule of sa.teamRules) {
      lines.push(rule, "");
    }
  }

  // ── Gotchas / TODOs (things that trip people up) ──
  if (sa && sa.todoComments.length > 0) {
    lines.push("## Known TODOs and Gotchas", "");
    lines.push("These are flagged in the code and may affect your work:", "");
    for (const t of sa.todoComments.slice(0, 15)) {
      lines.push(`- **${t.type}** \`${t.file}:${t.line}\` — ${t.text}`);
    }
    lines.push("");
  }

  // ── Key classes (only the truly important ones, with WHY) ──
  if (sa && sa.keyTypes.length > 0) {
    lines.push("## Key Classes", "");
    lines.push(
      "Largest and most-changed types — understand these before making changes:",
      "",
    );
    for (const t of sa.keyTypes.slice(0, 15)) {
      const ann =
        t.annotations.length > 0
          ? ` [${t.annotations.join(", ")}]`
          : "";
      const desc = t.description ? ` — ${t.description}` : "";
      lines.push(
        `- **${t.name}** (${t.linesOfCode} LOC) \`${t.file}\`${ann}${desc}`,
      );
      if (t.superTypes.length > 0) {
        lines.push(`  - extends: ${t.superTypes.join(", ")}`);
      }
    }
    lines.push("");
  }

  // ── Critical paths (inline, not a separate file) ──
  if (analysis.criticalPaths.length > 0) {
    lines.push("## Most Changed Files", "");
    lines.push("Extra care during reviews — these are the hot spots:", "");
    for (const p of analysis.criticalPaths.slice(0, 10)) {
      lines.push(`- \`${p.path}\` (${p.changeCount} changes)`);
    }
    lines.push("");
  }

  // ── Import graph: high fan-in files ──
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    lines.push("## Load-bearing Modules", "");
    lines.push("These files are imported by many others — changes here have wide blast radius:", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 10)) {
      lines.push(`- \`${file}\` — imported by ${fanIn} file${fanIn !== 1 ? "s" : ""}`);
    }
    lines.push("");
  }

  // ── Co-change coupling ──
  if (analysis.coChangePairs && analysis.coChangePairs.length > 0) {
    lines.push("## Frequently Co-changed Files", "");
    lines.push("These files are often modified together — changes to one may require changes to the other:", "");
    for (const pair of analysis.coChangePairs.slice(0, 10)) {
      const pct = Math.round(pair.strength * 100);
      lines.push(`- \`${pair.fileA}\` ↔ \`${pair.fileB}\` (${pair.count}× together, ${pct}% coupling)`);
    }
    lines.push("");
  }

  // ── Folder-level CLAUDE.md pointers ──
  if (sa && sa.hotpathDirs.length > 0) {
    lines.push("## Folder Context", "");
    lines.push(
      "These directories have their own CLAUDE.md with domain-specific context:",
      "",
    );
    const seenDirs = new Set<string>();
    for (const dir of sa.hotpathDirs) {
      if (seenDirs.has(dir)) continue;
      seenDirs.add(dir);
      lines.push(`- [\`${dir}/\`](../${dir}/CLAUDE.md)`);
    }
    lines.push("");
  }

  // ── Human-provided context ──
  if (humanAnswers?.architectureNotes) {
    lines.push("## Architecture Notes (from developer)", "");
    lines.push(humanAnswers.architectureNotes, "");
  }

  if (humanAnswers?.codePatterns && humanAnswers.codePatterns.length > 0) {
    lines.push("## Additional Patterns (from developer)", "");
    for (const p of humanAnswers.codePatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainContext && humanAnswers.domainContext.length > 0) {
    lines.push("## Domain Context (from developer)", "");
    for (const ctx of humanAnswers.domainContext) {
      lines.push(`- ${ctx}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainQA && humanAnswers.domainQA.length > 0) {
    lines.push("## Domain Knowledge (from developer)", "");
    for (const qa of humanAnswers.domainQA) {
      lines.push(`- **Q: ${qa.question}**`);
      lines.push(`  A: ${qa.answer}`, "");
    }
  }

  if (humanAnswers?.testingNotes) {
    lines.push("## Testing Notes (from developer)", "");
    lines.push(humanAnswers.testingNotes, "");
  }

  lines.push(AUTO_END);
  return lines.join("\n") + "\n";
}

// ── Root CLAUDE.md (repo root) ──────────────────────────────────────────────
// Minimal pointer — Claude Code reads .claude/CLAUDE.md automatically,
// but this root file helps when someone opens the repo directly.

export function renderRootClaudeMd(analysis: RepositoryAnalysis): string {
  const sa = analysis.sourceAnalysis;
  const desc = sa?.projectDescription;
  const lines: string[] = [
    DISCLAIMER,
    `# ${analysis.repoName}`,
    "",
    AUTO_START,
    "",
  ];

  if (desc) {
    lines.push(desc, "");
  }

  lines.push(`Full context for Claude Code: [.claude/CLAUDE.md](.claude/CLAUDE.md)`, "");

  lines.push(AUTO_END);
  return lines.join("\n") + "\n";
}

// ── Folder-level CLAUDE.md ──────────────────────────────────────────────────
// Only generated for directories where domain context actually helps.
// Focus on WHAT this code does and WHY, not file counts.

export function renderFolderClaudeMd(
  analysis: RepositoryAnalysis,
  module: ModuleInfo,
): string {
  const sa = analysis.sourceAnalysis;
  const dirName = module.path.split("/").pop()!;
  const lines: string[] = [
    DISCLAIMER,
    `# ${dirName}/`,
    "",
    AUTO_START,
    "",
  ];

  if (module.description) {
    lines.push(`**${module.description}**`, "");
  }

  // Subdirectory layout (only if there are meaningful children)
  const meaningfulChildren = module.children.filter(
    (c) => c.description && !c.description.endsWith("files"),
  );
  if (meaningfulChildren.length > 0) {
    lines.push("## Structure", "");
    for (const child of meaningfulChildren) {
      const childName = child.path.split("/").pop()!;
      lines.push(`- \`${childName}/\` — ${child.description}`);
    }
    lines.push("");
  }

  // Key types in this directory
  if (sa) {
    const typesInDir = sa.keyTypes
      .filter((t) => t.file.startsWith(module.path + "/") || t.file.startsWith(module.path))
      .slice(0, 10);
    if (typesInDir.length > 0) {
      lines.push("## Key Types", "");
      for (const t of typesInDir) {
        const relativePath = t.file.startsWith(module.path + "/")
          ? t.file.slice(module.path.length + 1)
          : t.file;
        const desc = t.description ? ` — ${t.description}` : "";
        const ann = t.annotations.length > 0 ? ` [${t.annotations.join(", ")}]` : "";
        lines.push(`- **${t.name}** (${t.linesOfCode} LOC) \`${relativePath}\`${ann}${desc}`);
        if (t.superTypes.length > 0) {
          lines.push(`  - extends: ${t.superTypes.join(", ")}`);
        }
      }
      lines.push("");
    }
  }

  // Most changed files (top 5)
  const hotFiles = module.keyFiles.slice(0, 5);
  if (hotFiles.length > 0) {
    lines.push("## Hot Files", "");
    for (const f of hotFiles) {
      const relativePath = f.startsWith(module.path + "/")
        ? f.slice(module.path.length + 1)
        : f;
      lines.push(`- \`${relativePath}\``);
    }
    lines.push("");
  }

  lines.push(AUTO_END);
  return lines.join("\n") + "\n";
}

// ── Helper to flatten module tree ──

export function flattenModules(modules: ModuleInfo[]): ModuleInfo[] {
  const flat: ModuleInfo[] = [];
  const recurse = (ms: ModuleInfo[]) => {
    for (const m of ms) {
      flat.push(m);
      recurse(m.children);
    }
  };
  recurse(modules);
  return flat;
}

// ── Architecture context ────────────────────────────────────────────────────

export function renderArchitectureContext(analysis: RepositoryAnalysis): string {
  const lines: string[] = [
    "<!-- Generated by claude-onboard — do not edit manually -->",
    `# Architecture — ${analysis.repoName}`,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // Style
  const arch = analysis.architecture;
  lines.push(`## Style: ${arch.style}`, "");

  // Entry points
  if (arch.entryPoints.length > 0) {
    lines.push("## Entry Points", "");
    for (const ep of arch.entryPoints) {
      lines.push(`- \`${ep}\``);
    }
    lines.push("");
  }

  // Layers
  if (arch.layers.length > 0) {
    lines.push("## Layers", "");
    for (const layer of arch.layers) {
      lines.push(`- ${layer}`);
    }
    lines.push("");
  }

  // Key modules from source analysis
  const sa = analysis.sourceAnalysis;
  if (sa?.modules && sa.modules.length > 0) {
    lines.push("## Key Modules", "");
    const sorted = [...sa.modules].sort((a, b) => b.changeCount - a.changeCount);
    for (const mod of sorted.slice(0, 15)) {
      lines.push(`- \`${mod.path}/\` — ${mod.description || mod.fileCount + " files"} (${mod.changeCount} changes)`);
    }
    lines.push("");
  }

  // Import graph: load-bearing modules
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    lines.push("## Load-bearing Modules (High Fan-in)", "");
    lines.push("Files imported by many others — changes here have wide blast radius:", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 15)) {
      lines.push(`- \`${file}\` — imported by ${fanIn} file${fanIn !== 1 ? "s" : ""}`);
    }
    lines.push("");
  }

  // Database patterns
  if (arch.databasePatterns.length > 0) {
    lines.push("## Database Patterns", "");
    for (const p of arch.databasePatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  // API patterns
  if (arch.apiPatterns.length > 0) {
    lines.push("## API Patterns", "");
    for (const p of arch.apiPatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  // Service map
  if (sa?.serviceMap && sa.serviceMap.length > 0) {
    lines.push("## Service Map", "");
    for (const svc of sa.serviceMap) {
      const ports = svc.port ? ` (port: ${svc.port})` : "";
      const deps = svc.dependsOn.length > 0 ? ` → depends on: ${svc.dependsOn.join(", ")}` : "";
      lines.push(`- **${svc.name}**${ports}${deps}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ── Patterns context ────────────────────────────────────────────────────────

export function renderPatternsContext(
  analysis: RepositoryAnalysis,
  humanAnswers?: HumanAnswers,
): string {
  const lines: string[] = [
    "<!-- Generated by claude-onboard — do not edit manually -->",
    `# Patterns & Conventions — ${analysis.repoName}`,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // Code patterns
  const sa = analysis.sourceAnalysis;
  if (sa?.codePatterns && sa.codePatterns.length > 0) {
    lines.push("## Code Patterns", "");
    for (const pattern of sa.codePatterns) {
      lines.push(`### ${pattern.name}`, "");
      lines.push(pattern.description, "");
      if (pattern.examples.length > 0) {
        lines.push("Examples:", "");
        for (const ex of pattern.examples) {
          lines.push(`- ${ex}`);
        }
        lines.push("");
      }
    }
  }

  // Conventions
  if (analysis.conventions.length > 0) {
    lines.push("## Conventions", "");
    for (const conv of analysis.conventions) {
      lines.push(`### ${conv.type}: ${conv.pattern}`, "");
      lines.push(conv.description, "");
      if (conv.examples.length > 0) {
        lines.push("Examples: " + conv.examples.slice(0, 3).map((e) => `\`${e}\``).join(", "), "");
      }
    }
  }

  // Commit patterns
  if (sa?.commitPatterns) {
    const cp = sa.commitPatterns;
    lines.push("## Commit & Branch Patterns", "");
    if (cp.mergeStrategy) lines.push(`- **Merge strategy**: ${cp.mergeStrategy}`);
    if (cp.style) lines.push(`- **Commit style**: ${cp.style}`);
    if (cp.branchPattern) {
      lines.push(`- **Branch pattern**: ${cp.branchPattern}`);
    }
    lines.push("");
  }

  // Team rules
  if (sa?.teamRules && sa.teamRules.length > 0) {
    lines.push("## Team Rules", "");
    for (const rule of sa.teamRules) {
      lines.push(rule, "");
    }
  }

  // Human-provided patterns
  if (humanAnswers?.codePatterns && humanAnswers.codePatterns.length > 0) {
    lines.push("## Additional Patterns (team-provided)", "");
    for (const p of humanAnswers.codePatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainContext && humanAnswers.domainContext.length > 0) {
    lines.push("## Domain Context", "");
    for (const d of humanAnswers.domainContext) {
      lines.push(`- ${d}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainQA && humanAnswers.domainQA.length > 0) {
    lines.push("## Domain Knowledge (Q&A)", "");
    for (const qa of humanAnswers.domainQA) {
      lines.push(`- **Q: ${qa.question}**`);
      lines.push(`  A: ${qa.answer}`, "");
    }
  }

  return lines.join("\n");
}

// ── Hot files context ───────────────────────────────────────────────────────

export function renderHotfilesContext(analysis: RepositoryAnalysis): string {
  const lines: string[] = [
    "<!-- Generated by claude-onboard — do not edit manually -->",
    `# Critical Paths & Hot Files — ${analysis.repoName}`,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // Most changed files
  if (analysis.criticalPaths.length > 0) {
    lines.push("## Most Changed Files", "");
    for (const cp of analysis.criticalPaths.slice(0, 30)) {
      lines.push(`- \`${cp.path}\` — ${cp.changeCount} changes`);
    }
    lines.push("");
  }

  // Co-change coupling
  if (analysis.coChangePairs && analysis.coChangePairs.length > 0) {
    lines.push("## Frequently Co-changed Files", "");
    lines.push("These files are often modified together:", "");
    for (const pair of analysis.coChangePairs.slice(0, 15)) {
      const pct = Math.round(pair.strength * 100);
      lines.push(`- \`${pair.fileA}\` ↔ \`${pair.fileB}\` (${pair.count}× together, ${pct}% coupling)`);
    }
    lines.push("");
  }

  // Load-bearing modules
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    lines.push("## Load-bearing Modules (Most Imported)", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 15)) {
      lines.push(`- \`${file}\` — imported by ${fanIn} file${fanIn !== 1 ? "s" : ""}`);
    }
    lines.push("");
  }

  // Key types
  const sa = analysis.sourceAnalysis;
  if (sa?.keyTypes && sa.keyTypes.length > 0) {
    lines.push("## Key Types", "");
    for (const kt of sa.keyTypes.slice(0, 20)) {
      const desc = kt.description ? ` — ${kt.description}` : "";
      lines.push(`- \`${kt.name}\` in \`${kt.file}\` (${kt.linesOfCode} LOC)${desc}`);
    }
    lines.push("");
  }

  // TODOs
  if (sa?.todoComments && sa.todoComments.length > 0) {
    lines.push("## Known TODOs", "");
    for (const todo of sa.todoComments.slice(0, 20)) {
      lines.push(`- \`${todo.file}:${todo.line}\` [${todo.type}] ${todo.text}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ── Stubs for removed files (return empty so documents.ts can still call them) ──

export function renderArchitectureMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderConventionsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderWorkflowsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderCriticalPathsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderContributorsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

// ── Commands ────────────────────────────────────────────────────────────────

export function renderOnboardCommand(): string {
  return `---
name: onboard
description: Get oriented with this codebase
---

You are onboarding to this repository. Read \`.claude/CLAUDE.md\` — it contains everything you need:
project purpose, commands, tech stack, architecture, code patterns, conventions, and gotchas.

After reading, give a concise summary of:
- What this project does and its domain concepts
- The key commands (build, test, run)
- Architecture and code patterns to follow
- Gotchas or quirks to watch out for
`;
}

export function renderStatusCommand(): string {
  return `---
name: status
description: Check documentation health
---

Check the health of the onboarding documentation in this repo:

1. Verify \`.claude/CLAUDE.md\` exists and read it.
2. Read \`.claude/.onboarder-meta.json\` to check when docs were last generated.
3. Run \`git log --oneline --since\` from that date to count commits since last update.
4. If more than 20 commits have landed since the last update, recommend running \`npx claude-onboard update\`.
5. Report whether docs appear stale.
`;
}

export function renderUpdateDocsCommand(): string {
  return `---
name: update-docs
description: Update documentation based on recent changes
---

Update the onboarding docs to reflect recent changes:

1. Read \`.claude/.onboarder-meta.json\` to find the last update timestamp.
2. Run \`git log --oneline\` since that date to see what changed.
3. Read \`.claude/CLAUDE.md\`.
4. Based on the recent commits, update any sections that are now outdated:
   - New modules or key files added
   - Changed architecture or dependencies
   - New conventions emerging from recent commits
5. Preserve any manual edits outside the \`<!-- onboarder:auto-start -->\` / \`<!-- onboarder:auto-end -->\` markers.
6. Alternatively, run \`npx claude-onboard update\` to regenerate automatically.
`;
}

export function renderPRReviewCommand(): string {
  return `---
name: pr-review
description: Review a pull request with project context
---

Review the current PR (or the PR number provided as $ARGUMENTS) using the project's conventions:

1. Read \`.claude/CLAUDE.md\` for project context, code patterns, and conventions.
2. Get the PR diff with \`gh pr diff $ARGUMENTS\` (or \`git diff\` if on a feature branch).
3. Review the changes against:
   - Code patterns listed in CLAUDE.md (DI style, error handling, test conventions)
   - Architecture rules (correct layer placement, dependency direction)
   - Hot files (are high-risk files being changed?)
4. Check if tests are included for new functionality.
5. Provide a structured review with: summary, concerns, suggestions, and approval recommendation.
`;
}

export function renderAskCommand(): string {
  return `---
name: ask
description: Answer questions about this codebase
---

Answer the following question about this repository: $ARGUMENTS

To answer, first read \`.claude/CLAUDE.md\` for project context.
Then check folder-level \`CLAUDE.md\` files in relevant source directories.
If the docs don't cover the question, explore the codebase directly.
`;
}
