import type { RepositoryAnalysis, HumanAnswers } from "../types.js";
import type { ModuleInfo } from "../analyzers/source.js";

const DISCLAIMER =
  "<!-- Auto-generated by claude-onboard. Do not edit between auto markers. -->";
export const AUTO_START = "<!-- onboarder:auto-start -->";
export const AUTO_END = "<!-- onboarder:auto-end -->";

function timestamp(): string {
  return new Date().toISOString();
}

function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const k = key(item);
    const existing = map.get(k);
    if (existing) {
      existing.push(item);
    } else {
      map.set(k, [item]);
    }
  }
  return map;
}

// ── Main CLAUDE.md (inside .claude/) ────────────────────────────────────────
// This is THE file. Everything Claude needs in one place.

export function renderClaudeMd(analysis: RepositoryAnalysis, humanAnswers?: HumanAnswers): string {
  const sa = analysis.sourceAnalysis;
  const lines: string[] = [
    DISCLAIMER,
    `# ${analysis.repoName}`,
    "",
    AUTO_START,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // ── Project identity ──
  const desc = humanAnswers?.projectDescription ?? sa?.projectDescription;
  if (desc) {
    lines.push(desc, "");
  } else {
    lines.push(
      `${analysis.repoName} is a **${analysis.primaryLanguage}** ${analysis.architecture.style}.`,
      "",
    );
  }

  if (sa?.packageStructure) {
    lines.push(`Root package: \`${sa.packageStructure}\``, "");
  }

  // ── Quick commands ──
  const hasBuildCmds = (sa && sa.buildCommands.length > 0) || (humanAnswers?.buildCommands && humanAnswers.buildCommands.length > 0);
  if (hasBuildCmds) {
    lines.push("## Commands", "");
    lines.push("```bash");
    const seen = new Set<string>();
    if (sa) {
      for (const cmd of sa.buildCommands) {
        if (seen.has(cmd.name)) continue;
        seen.add(cmd.name);
        const comment = cmd.source !== cmd.command ? `  # ${cmd.source}` : "";
        lines.push(`${cmd.command}${comment}`);
      }
    }
    if (humanAnswers?.buildCommands) {
      for (const cmd of humanAnswers.buildCommands) {
        if (!seen.has(cmd)) {
          lines.push(`${cmd}  # provided by developer`);
        }
      }
    }
    lines.push("```");
    lines.push("");
  }

  // ── Tech stack (grouped deps — only what's non-obvious) ──
  const depGroups = sa ? groupBy(sa.dependencies, (d) => d.group) : new Map<string, import("../analyzers/source.js").DependencyInfo[]>();
  if (depGroups.size > 0) {
    lines.push("## Tech Stack", "");
    for (const [group, deps] of depGroups) {
      if (group === "other" || group === "code-gen" || group === "logging") continue;
      const names = deps
        .map((d: import("../analyzers/source.js").DependencyInfo) => d.name.split(":").pop()!)
        .slice(0, 5)
        .join(", ");
      lines.push(
        `- **${group}**: ${names}${deps.length > 5 ? ` (+${deps.length - 5} more)` : ""}`,
      );
    }
    lines.push("");
  }

  // ── Architecture (concise — just the rules, not listings) ──
  lines.push("## Architecture", "");
  lines.push(`**Style**: ${analysis.architecture.style}`);
  if (analysis.architecture.layers.length > 0) {
    lines.push(
      `**Layers**: ${analysis.architecture.layers.join(" → ")}`,
    );
  }

  // Module map — only meaningful directories, not package hierarchy noise
  if (sa && sa.modules.length > 0) {
    lines.push("");
    lines.push("**Key modules**:");
    const seen = new Set<string>();
    const meaningful = flattenModules(sa.modules)
      .filter((m) => m.description && !m.description.endsWith("files"))
      .sort((a, b) => b.changeCount - a.changeCount)
      .filter((m) => {
        if (seen.has(m.path)) return false;
        seen.add(m.path);
        return true;
      })
      .slice(0, 12);
    for (const mod of meaningful) {
      lines.push(`- \`${mod.path}/\` — ${mod.description} (${mod.fileCount} files)`);
    }
  }
  lines.push("");

  // ── Code Patterns & Idioms (this is the gold — things Claude can't grep for) ──
  if (sa && sa.codePatterns.length > 0) {
    lines.push("## Code Patterns", "");
    lines.push("Follow these patterns when writing new code:", "");
    for (const p of sa.codePatterns) {
      lines.push(`### ${p.name}`, "");
      lines.push(p.description, "");
    }
  }

  // ── Conventions (merged — no separate file needed) ──
  if (analysis.conventions.length > 0) {
    lines.push("## Conventions", "");
    for (const c of analysis.conventions) {
      lines.push(`- **${c.type}**: ${c.description}`);
      if (c.examples.length > 0) {
        lines.push(`  - Example: \`${c.examples[0]}\``);
      }
    }

    // Commit patterns from deeper analysis
    if (sa?.commitPatterns) {
      const cp = sa.commitPatterns;
      if (cp.branchPattern) {
        lines.push(`- **branches**: ${cp.branchPattern}`);
      }
      if (cp.mergeStrategy !== "unknown") {
        lines.push(`- **merge strategy**: ${cp.mergeStrategy}`);
      }
    }
    lines.push("");
  }

  // ── Service map (microservices) ──
  if (sa && sa.serviceMap.length > 0) {
    lines.push("## Services", "");
    for (const svc of sa.serviceMap) {
      const port = svc.port ? `:${svc.port}` : "";
      const deps = svc.dependsOn.length > 0 ? ` → depends on: ${svc.dependsOn.join(", ")}` : "";
      lines.push(`- **${svc.name}**${port}${deps}`);
    }
    lines.push("");
  }

  // ── Team rules (code-review.rules, .cursor/rules) ──
  if (sa && sa.teamRules.length > 0) {
    lines.push("## Team Rules & Conventions", "");
    lines.push("These rules were found in the repo and should be followed:", "");
    for (const rule of sa.teamRules) {
      lines.push(rule, "");
    }
  }

  // ── Gotchas / TODOs (things that trip people up) ──
  if (sa && sa.todoComments.length > 0) {
    lines.push("## Known TODOs and Gotchas", "");
    lines.push("These are flagged in the code and may affect your work:", "");
    for (const t of sa.todoComments.slice(0, 15)) {
      lines.push(`- **${t.type}** \`${t.file}:${t.line}\` — ${t.text}`);
    }
    lines.push("");
  }

  // ── Key classes (only the truly important ones, with WHY) ──
  if (sa && sa.keyTypes.length > 0) {
    lines.push("## Key Classes", "");
    lines.push(
      "Largest and most-changed types — understand these before making changes:",
      "",
    );
    for (const t of sa.keyTypes.slice(0, 15)) {
      const ann =
        t.annotations.length > 0
          ? ` [${t.annotations.join(", ")}]`
          : "";
      const desc = t.description ? ` — ${t.description}` : "";
      lines.push(
        `- **${t.name}** (${t.linesOfCode} LOC) \`${t.file}\`${ann}${desc}`,
      );
      if (t.superTypes.length > 0) {
        lines.push(`  - extends: ${t.superTypes.join(", ")}`);
      }
    }
    lines.push("");
  }

  // ── Critical paths (inline, not a separate file) ──
  if (analysis.criticalPaths.length > 0) {
    lines.push("## Most Changed Files", "");
    lines.push("Extra care during reviews — these are the hot spots:", "");
    for (const p of analysis.criticalPaths.slice(0, 10)) {
      lines.push(`- \`${p.path}\` (${p.changeCount} changes)`);
    }
    lines.push("");
  }

  // ── Import graph: high fan-in files ──
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    lines.push("## Load-bearing Modules", "");
    lines.push("These files are imported by many others — changes here have wide blast radius:", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 10)) {
      lines.push(`- \`${file}\` — imported by ${fanIn} file${fanIn !== 1 ? "s" : ""}`);
    }
    lines.push("");
  }

  // ── Co-change coupling ──
  if (analysis.coChangePairs && analysis.coChangePairs.length > 0) {
    lines.push("## Frequently Co-changed Files", "");
    lines.push("These files are often modified together — changes to one may require changes to the other:", "");
    for (const pair of analysis.coChangePairs.slice(0, 10)) {
      const pct = Math.round(pair.strength * 100);
      lines.push(`- \`${pair.fileA}\` ↔ \`${pair.fileB}\` (${pair.count}× together, ${pct}% coupling)`);
    }
    lines.push("");
  }

  // ── Agents ──
  lines.push("## Agents", "");
  lines.push("Specialized agents are available in `.claude/agents/`. Use them for autonomous, delegated work:", "");
  lines.push("- **reviewer** — Spawn when reviewing PRs or code changes. Knows this repo's conventions, critical paths, and co-change coupling.");
  if (analysis.testFrameworks.length > 0) {
    lines.push("- **test-writer** — Spawn when writing or updating tests. Knows the test framework, structure, and patterns.");
  }
  lines.push("- **context-maintainer** — Spawn after init or update. Extracts context from code, git history, and developer knowledge. Populates it into the right files.");
  lines.push("- **security-auditor** — Spawn for security reviews. Knows this repo's tech stack and attack surface.");
  lines.push("");

  // ── Folder-level CLAUDE.md pointers ──
  if (sa && sa.hotpathDirs.length > 0) {
    lines.push("## Folder Context", "");
    lines.push(
      "These directories have their own CLAUDE.md with domain-specific context:",
      "",
    );
    const seenDirs = new Set<string>();
    for (const dir of sa.hotpathDirs) {
      if (seenDirs.has(dir)) continue;
      seenDirs.add(dir);
      lines.push(`- [\`${dir}/\`](../${dir}/CLAUDE.md)`);
    }
    lines.push("");
  }

  // ── Framework decisions (filtered from domainQA) ──
  const frameworkQA = humanAnswers?.domainQA?.filter((qa) => qa.question.match(/^\[.+?\] /));
  const otherQA = humanAnswers?.domainQA?.filter((qa) => !qa.question.match(/^\[.+?\] /));
  if (frameworkQA && frameworkQA.length > 0) {
    lines.push("## Framework Decisions", "");
    lines.push("Project-specific choices — follow these when writing new code:", "");
    for (const qa of frameworkQA) {
      // Strip the [Framework] prefix for cleaner display
      const cleanQ = qa.question.replace(/^\[.+?\] /, "");
      const framework = qa.question.match(/^\[(.+?)\]/)?.[1] ?? "";
      lines.push(`- **${framework}**: ${cleanQ}`);
      lines.push(`  → ${qa.answer}`, "");
    }
  }

  // ── Runtime docs hint ──
  if (analysis.frameworks.length > 0) {
    const fwList = analysis.frameworks.slice(0, 3).join(", ");
    lines.push("## Runtime Docs", "");
    lines.push(`When making framework-specific changes (${fwList}), use Context7 MCP to fetch latest documentation before implementing.`, "");
  }

  // ── Human-provided context ──
  if (humanAnswers?.architectureNotes) {
    lines.push("## Architecture Notes (from developer)", "");
    lines.push(humanAnswers.architectureNotes, "");
  }

  if (humanAnswers?.codePatterns && humanAnswers.codePatterns.length > 0) {
    lines.push("## Additional Patterns (from developer)", "");
    for (const p of humanAnswers.codePatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainContext && humanAnswers.domainContext.length > 0) {
    lines.push("## Domain Context (from developer)", "");
    for (const ctx of humanAnswers.domainContext) {
      lines.push(`- ${ctx}`);
    }
    lines.push("");
  }

  if (otherQA && otherQA.length > 0) {
    lines.push("## Domain Knowledge (from developer)", "");
    for (const qa of otherQA) {
      lines.push(`- **Q: ${qa.question}**`);
      lines.push(`  A: ${qa.answer}`, "");
    }
  }

  if (humanAnswers?.testingNotes) {
    lines.push("## Testing Notes (from developer)", "");
    lines.push(humanAnswers.testingNotes, "");
  }

  lines.push(AUTO_END);
  return lines.join("\n") + "\n";
}

// ── Root CLAUDE.md (repo root) ──────────────────────────────────────────────
// Minimal pointer — Claude Code reads .claude/CLAUDE.md automatically,
// but this root file helps when someone opens the repo directly.

export function renderRootClaudeMd(analysis: RepositoryAnalysis): string {
  const sa = analysis.sourceAnalysis;
  const desc = sa?.projectDescription;
  const lines: string[] = [
    DISCLAIMER,
    `# ${analysis.repoName}`,
    "",
    AUTO_START,
    "",
  ];

  if (desc) {
    lines.push(desc, "");
  }

  lines.push(`Full context for Claude Code: [.claude/CLAUDE.md](.claude/CLAUDE.md)`, "");

  lines.push(AUTO_END);
  return lines.join("\n") + "\n";
}

// ── Folder-level CLAUDE.md ──────────────────────────────────────────────────
// Only generated for directories where domain context actually helps.
// Focus on WHAT this code does and WHY, not file counts.

export function renderFolderClaudeMd(
  analysis: RepositoryAnalysis,
  module: ModuleInfo,
): string {
  const sa = analysis.sourceAnalysis;
  const dirName = module.path.split("/").pop()!;
  const lines: string[] = [
    DISCLAIMER,
    `# ${dirName}/`,
    "",
    AUTO_START,
    "",
  ];

  if (module.description) {
    lines.push(`**${module.description}**`, "");
  }

  // Subdirectory layout (only if there are meaningful children)
  const meaningfulChildren = module.children.filter(
    (c) => c.description && !c.description.endsWith("files"),
  );
  if (meaningfulChildren.length > 0) {
    lines.push("## Structure", "");
    for (const child of meaningfulChildren) {
      const childName = child.path.split("/").pop()!;
      lines.push(`- \`${childName}/\` — ${child.description}`);
    }
    lines.push("");
  }

  // Key types in this directory
  if (sa) {
    const typesInDir = sa.keyTypes
      .filter((t) => t.file.startsWith(module.path + "/") || t.file.startsWith(module.path))
      .slice(0, 10);
    if (typesInDir.length > 0) {
      lines.push("## Key Types", "");
      for (const t of typesInDir) {
        const relativePath = t.file.startsWith(module.path + "/")
          ? t.file.slice(module.path.length + 1)
          : t.file;
        const desc = t.description ? ` — ${t.description}` : "";
        const ann = t.annotations.length > 0 ? ` [${t.annotations.join(", ")}]` : "";
        lines.push(`- **${t.name}** (${t.linesOfCode} LOC) \`${relativePath}\`${ann}${desc}`);
        if (t.superTypes.length > 0) {
          lines.push(`  - extends: ${t.superTypes.join(", ")}`);
        }
      }
      lines.push("");
    }
  }

  // Most changed files (top 5)
  const hotFiles = module.keyFiles.slice(0, 5);
  if (hotFiles.length > 0) {
    lines.push("## Hot Files", "");
    for (const f of hotFiles) {
      const relativePath = f.startsWith(module.path + "/")
        ? f.slice(module.path.length + 1)
        : f;
      lines.push(`- \`${relativePath}\``);
    }
    lines.push("");
  }

  lines.push(AUTO_END);
  return lines.join("\n") + "\n";
}

// ── Helper to flatten module tree ──

export function flattenModules(modules: ModuleInfo[]): ModuleInfo[] {
  const flat: ModuleInfo[] = [];
  const recurse = (ms: ModuleInfo[]) => {
    for (const m of ms) {
      flat.push(m);
      recurse(m.children);
    }
  };
  recurse(modules);
  return flat;
}

// ── Architecture context ────────────────────────────────────────────────────

export function renderArchitectureContext(analysis: RepositoryAnalysis): string {
  const lines: string[] = [
    "<!-- Generated by claude-onboard — do not edit manually -->",
    `# Architecture — ${analysis.repoName}`,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // Style
  const arch = analysis.architecture;
  lines.push(`## Style: ${arch.style}`, "");

  // Entry points
  if (arch.entryPoints.length > 0) {
    lines.push("## Entry Points", "");
    for (const ep of arch.entryPoints) {
      lines.push(`- \`${ep}\``);
    }
    lines.push("");
  }

  // Layers
  if (arch.layers.length > 0) {
    lines.push("## Layers", "");
    for (const layer of arch.layers) {
      lines.push(`- ${layer}`);
    }
    lines.push("");
  }

  // Key modules from source analysis
  const sa = analysis.sourceAnalysis;
  if (sa?.modules && sa.modules.length > 0) {
    lines.push("## Key Modules", "");
    const sorted = [...sa.modules].sort((a, b) => b.changeCount - a.changeCount);
    for (const mod of sorted.slice(0, 15)) {
      lines.push(`- \`${mod.path}/\` — ${mod.description || mod.fileCount + " files"} (${mod.changeCount} changes)`);
    }
    lines.push("");
  }

  // Import graph: load-bearing modules
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    lines.push("## Load-bearing Modules (High Fan-in)", "");
    lines.push("Files imported by many others — changes here have wide blast radius:", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 15)) {
      lines.push(`- \`${file}\` — imported by ${fanIn} file${fanIn !== 1 ? "s" : ""}`);
    }
    lines.push("");
  }

  // Database patterns
  if (arch.databasePatterns.length > 0) {
    lines.push("## Database Patterns", "");
    for (const p of arch.databasePatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  // API patterns
  if (arch.apiPatterns.length > 0) {
    lines.push("## API Patterns", "");
    for (const p of arch.apiPatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  // Service map
  if (sa?.serviceMap && sa.serviceMap.length > 0) {
    lines.push("## Service Map", "");
    for (const svc of sa.serviceMap) {
      const ports = svc.port ? ` (port: ${svc.port})` : "";
      const deps = svc.dependsOn.length > 0 ? ` → depends on: ${svc.dependsOn.join(", ")}` : "";
      lines.push(`- **${svc.name}**${ports}${deps}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ── Patterns context ────────────────────────────────────────────────────────

export function renderPatternsContext(
  analysis: RepositoryAnalysis,
  humanAnswers?: HumanAnswers,
): string {
  const lines: string[] = [
    "<!-- Generated by claude-onboard — do not edit manually -->",
    `# Patterns & Conventions — ${analysis.repoName}`,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // Code patterns
  const sa = analysis.sourceAnalysis;
  if (sa?.codePatterns && sa.codePatterns.length > 0) {
    lines.push("## Code Patterns", "");
    for (const pattern of sa.codePatterns) {
      lines.push(`### ${pattern.name}`, "");
      lines.push(pattern.description, "");
      if (pattern.examples.length > 0) {
        lines.push("Examples:", "");
        for (const ex of pattern.examples) {
          lines.push(`- ${ex}`);
        }
        lines.push("");
      }
    }
  }

  // Conventions
  if (analysis.conventions.length > 0) {
    lines.push("## Conventions", "");
    for (const conv of analysis.conventions) {
      lines.push(`### ${conv.type}: ${conv.pattern}`, "");
      lines.push(conv.description, "");
      if (conv.examples.length > 0) {
        lines.push("Examples: " + conv.examples.slice(0, 3).map((e) => `\`${e}\``).join(", "), "");
      }
    }
  }

  // Commit patterns
  if (sa?.commitPatterns) {
    const cp = sa.commitPatterns;
    lines.push("## Commit & Branch Patterns", "");
    if (cp.mergeStrategy) lines.push(`- **Merge strategy**: ${cp.mergeStrategy}`);
    if (cp.style) lines.push(`- **Commit style**: ${cp.style}`);
    if (cp.branchPattern) {
      lines.push(`- **Branch pattern**: ${cp.branchPattern}`);
    }
    lines.push("");
  }

  // Team rules
  if (sa?.teamRules && sa.teamRules.length > 0) {
    lines.push("## Team Rules", "");
    for (const rule of sa.teamRules) {
      lines.push(rule, "");
    }
  }

  // Human-provided patterns
  if (humanAnswers?.codePatterns && humanAnswers.codePatterns.length > 0) {
    lines.push("## Additional Patterns (team-provided)", "");
    for (const p of humanAnswers.codePatterns) {
      lines.push(`- ${p}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainContext && humanAnswers.domainContext.length > 0) {
    lines.push("## Domain Context", "");
    for (const d of humanAnswers.domainContext) {
      lines.push(`- ${d}`);
    }
    lines.push("");
  }

  if (humanAnswers?.domainQA && humanAnswers.domainQA.length > 0) {
    lines.push("## Domain Knowledge (Q&A)", "");
    for (const qa of humanAnswers.domainQA) {
      lines.push(`- **Q: ${qa.question}**`);
      lines.push(`  A: ${qa.answer}`, "");
    }
  }

  return lines.join("\n");
}

// ── Hot files context ───────────────────────────────────────────────────────

export function renderHotfilesContext(analysis: RepositoryAnalysis): string {
  const lines: string[] = [
    "<!-- Generated by claude-onboard — do not edit manually -->",
    `# Critical Paths & Hot Files — ${analysis.repoName}`,
    "",
    `> Last generated: ${timestamp()}`,
    "",
  ];

  // Most changed files
  if (analysis.criticalPaths.length > 0) {
    lines.push("## Most Changed Files", "");
    for (const cp of analysis.criticalPaths.slice(0, 30)) {
      lines.push(`- \`${cp.path}\` — ${cp.changeCount} changes`);
    }
    lines.push("");
  }

  // Co-change coupling
  if (analysis.coChangePairs && analysis.coChangePairs.length > 0) {
    lines.push("## Frequently Co-changed Files", "");
    lines.push("These files are often modified together:", "");
    for (const pair of analysis.coChangePairs.slice(0, 15)) {
      const pct = Math.round(pair.strength * 100);
      lines.push(`- \`${pair.fileA}\` ↔ \`${pair.fileB}\` (${pair.count}× together, ${pct}% coupling)`);
    }
    lines.push("");
  }

  // Load-bearing modules
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    lines.push("## Load-bearing Modules (Most Imported)", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 15)) {
      lines.push(`- \`${file}\` — imported by ${fanIn} file${fanIn !== 1 ? "s" : ""}`);
    }
    lines.push("");
  }

  // Key types
  const sa = analysis.sourceAnalysis;
  if (sa?.keyTypes && sa.keyTypes.length > 0) {
    lines.push("## Key Types", "");
    for (const kt of sa.keyTypes.slice(0, 20)) {
      const desc = kt.description ? ` — ${kt.description}` : "";
      lines.push(`- \`${kt.name}\` in \`${kt.file}\` (${kt.linesOfCode} LOC)${desc}`);
    }
    lines.push("");
  }

  // TODOs
  if (sa?.todoComments && sa.todoComments.length > 0) {
    lines.push("## Known TODOs", "");
    for (const todo of sa.todoComments.slice(0, 20)) {
      lines.push(`- \`${todo.file}:${todo.line}\` [${todo.type}] ${todo.text}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ── Stubs for removed files (return empty so documents.ts can still call them) ──

export function renderArchitectureMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderConventionsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderWorkflowsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderCriticalPathsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

export function renderContributorsMd(_analysis: RepositoryAnalysis): string {
  return "";
}

// ── Commands ────────────────────────────────────────────────────────────────

export function renderOnboardCommand(): string {
  return `---
name: onboard
description: Get oriented with this codebase — or run initial setup if not yet onboarded
---

First, check if \`.claude/CLAUDE.md\` exists.

**If it does NOT exist (first-time setup):**
1. Run \`npx claude-onboard init --no-interactive\` to generate baseline documentation
2. Then spawn the **context-maintainer** agent to evaluate documentation quality, ask targeted questions, and improve coverage until the confidence score reaches the target

**If it already exists:**
1. Read \`.claude/CLAUDE.md\` — it contains everything you need: project purpose, commands, tech stack, architecture, code patterns, conventions, and gotchas
2. Give a concise summary of:
   - What this project does and its domain concepts
   - The key commands (build, test, run)
   - Architecture and code patterns to follow
   - Gotchas or quirks to watch out for
`;
}

export function renderStatusCommand(): string {
  return `---
name: status
description: Check documentation health
---

Check the health of the onboarding documentation in this repo:

1. Verify \`.claude/CLAUDE.md\` exists and read it.
2. Read \`.claude/.onboarder-meta.json\` to check when docs were last generated.
3. Run \`git log --oneline --since\` from that date to count commits since last update.
4. If more than 20 commits have landed since the last update, recommend running \`npx claude-onboard update\`.
5. Report whether docs appear stale.
`;
}

export function renderUpdateContextCommand(): string {
  return `---
name: update-context
description: Update documentation and evaluate quality
---

Update the onboarding docs and ensure they're high quality:

1. Run \`npx claude-onboard update\` to regenerate auto-sections from static analysis
2. Spawn the **context-maintainer** agent to evaluate documentation quality against the actual code, ask targeted questions about gaps, and improve coverage until the confidence score reaches the target
`;
}

export function renderPRReviewCommand(): string {
  return `---
name: pr-review
description: Review a pull request with project context
---

Review the current PR (or the PR number provided as $ARGUMENTS) using the project's conventions:

1. Read \`.claude/CLAUDE.md\` for project context, code patterns, and conventions.
2. Get the PR diff with \`gh pr diff $ARGUMENTS\` (or \`git diff\` if on a feature branch).
3. Review the changes against:
   - Code patterns listed in CLAUDE.md (DI style, error handling, test conventions)
   - Architecture rules (correct layer placement, dependency direction)
   - Hot files (are high-risk files being changed?)
4. Check if tests are included for new functionality.
5. Provide a structured review with: summary, concerns, suggestions, and approval recommendation.
`;
}

export function renderAskCommand(): string {
  return `---
name: ask
description: Answer questions about this codebase
---

Answer the following question about this repository: $ARGUMENTS

To answer, first read \`.claude/CLAUDE.md\` for project context.
Then check folder-level \`CLAUDE.md\` files in relevant source directories.
If the docs don't cover the question, explore the codebase directly.
`;
}

// ── Agent render functions ───────────────────────────────────────────────────

interface AgentFrontmatter {
  name: string;
  description: string;
  tools: string[];
  model?: string;
  permissionMode?: string;
  maxTurns?: number;
  memory?: string;
  isolation?: string;
}

function agentFrontmatter(opts: AgentFrontmatter): string {
  const lines = [
    "---",
    `name: ${opts.name}`,
    `description: "${opts.description}"`,
    `tools: ${opts.tools.join(", ")}`,
  ];
  if (opts.model) lines.push(`model: ${opts.model}`);
  if (opts.permissionMode) lines.push(`permissionMode: ${opts.permissionMode}`);
  if (opts.maxTurns) lines.push(`maxTurns: ${opts.maxTurns}`);
  if (opts.memory) lines.push(`memory: ${opts.memory}`);
  if (opts.isolation) lines.push(`isolation: ${opts.isolation}`);
  lines.push("---");
  return lines.join("\n");
}

function agentBody(sections: string[]): string {
  return [
    "",
    AUTO_START,
    "",
    ...sections,
    "",
    AUTO_END,
    "",
  ].join("\n");
}

export function renderReviewerAgent(analysis: RepositoryAnalysis): string {
  const sa = analysis.sourceAnalysis;
  const sections: string[] = [
    `# Code Reviewer — ${analysis.repoName}`,
    "",
    `You are a code reviewer with deep knowledge of this repository's conventions, architecture, and critical paths.`,
    "",
    "## Architecture",
    "",
    `- **Style**: ${analysis.architecture.style}`,
  ];

  if (analysis.architecture.layers.length > 0) {
    sections.push(`- **Layers**: ${analysis.architecture.layers.join(" → ")}`);
  }

  // Conventions
  if (analysis.conventions.length > 0) {
    sections.push("", "## Conventions", "");
    for (const c of analysis.conventions) {
      sections.push(`- **${c.type}**: ${c.description}`);
      if (c.examples.length > 0) {
        sections.push(`  - Pattern: \`${c.examples[0]}\``);
      }
    }
    if (sa?.commitPatterns?.branchPattern) {
      sections.push(`- **branches**: ${sa.commitPatterns.branchPattern}`);
    }
  }

  // Critical paths
  if (analysis.criticalPaths.length > 0) {
    sections.push("", "## Critical Paths (high change frequency)", "");
    sections.push("Extra scrutiny required when these files are touched:", "");
    for (const p of analysis.criticalPaths.slice(0, 10)) {
      sections.push(`- \`${p.path}\` (${p.changeCount} changes)`);
    }
  }

  // Co-change pairs
  if (analysis.coChangePairs && analysis.coChangePairs.length > 0) {
    sections.push("", "## Co-change Coupling", "");
    sections.push("If one file in a pair is changed, check the other:", "");
    for (const pair of analysis.coChangePairs.slice(0, 10)) {
      const pct = Math.round(pair.strength * 100);
      sections.push(`- \`${pair.fileA}\` ↔ \`${pair.fileB}\` (${pct}% coupling)`);
    }
  }

  // Key types
  if (sa && sa.keyTypes.length > 0) {
    sections.push("", "## Key Types", "");
    for (const t of sa.keyTypes.slice(0, 10)) {
      const desc = t.description ? ` — ${t.description}` : "";
      sections.push(`- **${t.name}** \`${t.file}\` (${t.linesOfCode} LOC)${desc}`);
    }
  }

  // Load-bearing modules
  if (analysis.importGraph && analysis.importGraph.topByFanIn.length > 0) {
    sections.push("", "## Load-bearing Modules", "");
    sections.push("Changes here have wide blast radius:", "");
    for (const { file, fanIn } of analysis.importGraph.topByFanIn.slice(0, 8)) {
      sections.push(`- \`${file}\` — imported by ${fanIn} files`);
    }
  }

  sections.push(
    "",
    "## How to Get the Diff",
    "",
    "Determine what to review based on how you were invoked:",
    "- If given a PR number: `gh pr diff <number>`",
    "- If on a feature branch: `git diff $(git merge-base HEAD " + analysis.defaultBranch + ")..HEAD`",
    "- If reviewing staged changes: `git diff --cached`",
    "- If no context given: `git diff HEAD~1` for the last commit",
    "",
    "## Review Process",
    "",
    "### Step 1: Understand the change",
    "Read the full diff. Summarize WHAT changed and WHY (infer from commit messages, PR description, or code context).",
    "",
    "### Step 2: Check conventions",
    "Cross-reference every changed file against the conventions listed above. Flag deviations with the specific convention violated.",
    "",
    "### Step 3: Critical path analysis",
    "If ANY file in the Critical Paths list above is modified:",
    "- Verify the change has test coverage",
    "- Check if the change could affect downstream consumers",
    "- Flag if the change modifies a public API or interface",
    "",
    "### Step 4: Co-change validation",
    "For every changed file, check if it appears in a co-change pair above. If its pair is NOT in the diff, flag it as: \"Warning: `fileA` was changed but its co-change partner `fileB` was not. These files are modified together " + "N% of the time — verify this is intentional.\"",
    "",
    "### Step 5: Blast radius check",
    "If any load-bearing module (high fan-in) is modified, search for all importers using `Grep` and assess whether the change is backward-compatible.",
    "",
    "### Step 6: Read code patterns",
    "Read `.claude/context/patterns.md` and verify new code follows established patterns.",
    "",
    "## Output Format",
    "",
    "Structure your review as:",
    "```",
    "## Summary",
    "(1-2 sentence description of the change)",
    "",
    "## Risk Assessment: LOW | MEDIUM | HIGH | CRITICAL",
    "(Based on: critical paths touched, blast radius, complexity)",
    "",
    "## Findings",
    "### [SEVERITY] Finding title",
    "- **File**: `path/to/file.ext:line`",
    "- **Issue**: What's wrong",
    "- **Suggestion**: How to fix it",
    "",
    "## Co-change Warnings",
    "(Any missed co-change partners)",
    "",
    "## Verdict: APPROVE | REQUEST_CHANGES | NEEDS_DISCUSSION",
    "```",
  );

  return agentFrontmatter({
    name: "reviewer",
    description: "Code reviewer with deep knowledge of this repo's conventions and critical paths",
    tools: ["Read", "Glob", "Grep", "Bash"],
    model: "sonnet",
    permissionMode: "plan",
    maxTurns: 20,
    isolation: "worktree",
  }) + agentBody(sections);
}

export function renderTestWriterAgent(analysis: RepositoryAnalysis): string {
  const sa = analysis.sourceAnalysis;
  const sections: string[] = [
    `# Test Writer — ${analysis.repoName}`,
    "",
    `You write tests that match this repository's exact testing patterns and conventions.`,
    "",
    "## Test Stack",
    "",
    `- **Frameworks**: ${analysis.testFrameworks.join(", ")}`,
    `- **Test structure**: ${analysis.architecture.testStructure}`,
    `- **Coverage level**: ${analysis.testCoverage}`,
  ];

  // Build commands for running tests
  if (sa) {
    const testCmds = sa.buildCommands.filter(
      (cmd) => cmd.name.includes("test") || cmd.command.includes("test"),
    );
    if (testCmds.length > 0) {
      sections.push("", "## Test Commands", "");
      for (const cmd of testCmds) {
        sections.push(`- \`${cmd.command}\``);
      }
    }
  }

  // Code patterns related to testing
  if (sa?.codePatterns) {
    const testPatterns = sa.codePatterns.filter(
      (p) => p.name.toLowerCase().includes("test") || p.description.toLowerCase().includes("test"),
    );
    if (testPatterns.length > 0) {
      sections.push("", "## Test Patterns in This Repo", "");
      for (const p of testPatterns) {
        sections.push(`### ${p.name}`, "", p.description, "");
      }
    }
  }

  sections.push(
    "",
    "## Process",
    "",
    "### Step 1: Understand the target",
    "Read the source file you are writing tests for. Understand its public API, dependencies, and edge cases.",
    "",
    "### Step 2: Find existing test examples",
    `Use \`Glob\` to find existing test files (patterns: \`**/*.test.*\`, \`**/*.spec.*\`, \`**/test_*\`, \`**/*Test.java\`). Read 2-3 examples to understand:`,
    "- Import style and test setup patterns",
    "- How mocks/stubs are created",
    "- Assertion style (expect vs assert vs assertThat)",
    "- Test naming conventions (describe/it, should-style, method_condition_expected)",
    "- Setup/teardown patterns (beforeEach, @BeforeEach, setUp)",
    "",
    "### Step 3: Write tests",
    `Place tests ${analysis.architecture.testStructure === "colocated" ? "next to the source file" : "in the corresponding test directory, mirroring the source path"}.`,
    "",
    "For each public method/function, write:",
    "- **Happy path**: Normal input, expected output",
    "- **Edge cases**: Empty input, null/undefined, boundary values",
    "- **Error cases**: Invalid input, expected exceptions",
    "- **Integration points**: If the function calls external services, test with mocks",
    "",
    "### Step 4: Verify",
    "Run the test suite to ensure all new tests pass and no existing tests break.",
    analysis.testFrameworks.length > 0
      ? `Use the test framework: ${analysis.testFrameworks.join(", ")}`
      : "",
    "",
    "## Output Format",
    "",
    "After writing tests, report:",
    "```",
    "## Tests Written",
    "- `path/to/test/file`: N tests (N pass, N fail)",
    "",
    "## Coverage",
    "- Methods covered: list",
    "- Edge cases covered: list",
    "- Not covered (and why): list",
    "```",
  );

  return agentFrontmatter({
    name: "test-writer",
    description: "Test writer that generates tests matching this repo's exact testing patterns",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    model: "sonnet",
    maxTurns: 20,
  }) + agentBody(sections);
}

export function renderContextMaintainerAgent(analysis: RepositoryAnalysis): string {
  const sa = analysis.sourceAnalysis;
  const sections: string[] = [
    `# Context Maintainer — ${analysis.repoName}`,
    "",
    "You are a senior developer onboarding this repository. Your job is to extract every piece of context that would help a new team member (or Claude) be productive immediately — from source code, git history, configuration, and developer knowledge — then populate it into the right files.",
    "",
    "## Your Mission",
    "",
    "Static analysis gets you 60-70% of the way. Your job is to close the remaining gap by:",
    "1. **Reading code** that static analysis summarized but didn't deeply understand",
    "2. **Mining git history** for patterns, decisions, and evolution that shaped the codebase",
    "3. **Asking the developer** targeted questions about things only humans know: business logic, deployment gotchas, tribal knowledge",
    "4. **Populating context** into the right files so every future Claude session starts with full understanding",
    "",
    "## Context Extraction Playbook",
    "",
    "### Phase 1: Understand what's already captured",
    "",
    "Read the existing context files:",
    "- `.claude/CLAUDE.md` — main project context",
    "- `.claude/context/architecture.md` — entry points, layers, load-bearing modules",
    "- `.claude/context/patterns.md` — code idioms, conventions, anti-patterns",
    "- `.claude/context/hotfiles.md` — critical paths, co-change coupling",
    "- Any additional `.claude/context/*.md` files — the context-maintainer may have created topic-specific files in previous runs (e.g., `decisions.md`, `tech-debt.md`, `contributor-map.md`)",
  ];

  if (sa && sa.hotpathDirs.length > 0) {
    sections.push("- Folder-level CLAUDE.md files (check for manual sections outside auto-markers — these contain human-provided context):");
    for (const dir of sa.hotpathDirs) {
      sections.push(`  - \`${dir}/CLAUDE.md\``);
    }
  }

  sections.push(
    "",
    "### Phase 2: Mine the codebase for missing context",
    "",
    "**Git history** — the richest source of context static analysis misses:",
    "",
    "First, determine the default branch:",
    "- `git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@'` or fall back to `main`/`master`",
    "",
    "Then mine the default branch history for deep context:",
    "- `git log --oneline -30` — recent trajectory and focus areas",
    "- `git log --all --oneline --graph -20` — branching patterns, release cadence",
    "- `git log --diff-filter=D --name-only -20` — recently deleted files (reveals refactors in progress)",
    "- `git log --format='%s' -50 | sort | uniq -c | sort -rn` — recurring commit themes",
    "- `git log --format='%H %s' --no-merges -100` — scan the last 100 commits on the default branch for major changes",
    "- `git log --numstat -50` — identify which files receive the most churn (lines added/removed)",
    "- `git log --diff-filter=A --name-only --format='' -50 | sort | head -20` — recently added files (new modules, features in progress)",
    "- `git log --grep='breaking\\|migrate\\|deprecat' --oneline -20` — commits that mention breaking changes, migrations, or deprecations",
    "- `git shortlog -sn --no-merges -20` — identify top contributors and knowledge owners",
    "- Look for migration commits, large refactors, and \"fix:\" patterns that reveal pain points",
    "",
    "After running the commands above to identify hotspots and patterns, the next step is to read actual diffs:",
    "",
    "**Read actual code diffs** — commit messages alone miss the real context.",
    "",
    "First, check if `.claude/.onboarder-meta.json` exists. This determines your scope:",
    "",
    "**If `.onboarder-meta.json` does NOT exist (initial onboard)** — do a comprehensive walk of the last 200-400 commits:",
    "",
    "1. **Get the full commit list**: `git log --oneline --no-merges -400` on the default branch",
    "2. **Walk through every commit's diff** — batch them in groups of ~20:",
    "   - `git log --oneline --no-merges --skip=0 -20` then `git show <hash> --stat` for each, and `git show <hash>` for the full diff",
    "   - Work through all 200-400 commits systematically — do not skip or sample",
    "   - For very large diffs, use `git show <hash> --stat` first, then read diffs for the most important files: `git show <hash> -- <file>`",
    "3. **As you read, write findings directly into the right place** — don't just take mental notes.",
    "",
    "   You decide where each finding belongs based on its scope:",
    "   - **Folder-specific** findings (a module's internal patterns, gotchas for a specific directory, how a particular service evolved) → write to the `CLAUDE.md` in that folder, outside the auto-markers. This is progressive disclosure — agents working in that folder get the context they need without loading everything.",
    "   - **Cross-cutting** findings (project-wide conventions, architectural decisions that span modules, overall patterns) → write to `.claude/context/` files. Enrich existing files (`architecture.md`, `patterns.md`, `hotfiles.md`) or create new topic-specific files when the finding doesn't fit.",
    "   - **New topic files**: if you discover a theme that deserves its own file (e.g., contributor knowledge map, tech debt tracker, decision log), create it in `.claude/context/`. Name it descriptively. You own the file structure — there's no fixed list.",
    "",
    "   Write as you go — each batch of ~20 commits should result in file updates. Don't wait until the end.",
    "",
    "   What to look for in each commit:",
    "   - Recurring patterns: how errors are handled, how tests are structured, how features are added",
    "   - Refactoring patterns: what gets cleaned up, what gets left alone",
    "   - Review feedback patterns: if squash/merge commits show iteration, note what reviewers care about",
    "4. **Compare file evolution** for the most-churned files:",
    "   - `git log --oneline <file>` — full history for that file",
    "   - `git diff <earliest-hash>..<latest-hash> -- <file>` — see the accumulated evolution",
    "5. **Read merge commit diffs** to understand feature-level changes: `git log --merges --oneline -30` then `git diff <merge>^..<merge>`",
    "",
    "This is the most time-intensive phase but also the most valuable — the patterns you extract here are what make the generated context actually useful versus generic.",
    "",
    "**If `.onboarder-meta.json` exists (subsequent update)** — only read diffs since the last update:",
    "",
    "1. Read `lastUpdated` from `.claude/.onboarder-meta.json`",
    "2. `git log --oneline --no-merges --since=\"<lastUpdated>\" -100` — get commits since last run (capped at 100)",
    "3. Read diffs for all commits in that range using the same detailed approach as steps 2-4 above, but scoped to the new commits only",
    "4. Focus on what changed: new patterns, new modules, convention shifts, or regressions from established patterns",
    "",
    "**Source code** — read the files that matter most:",
    "- Entry points (main, index, server files) — understand the application bootstrap",
    "- Configuration files (env templates, docker-compose, CI config) — understand deployment",
    "- The top 5 most-changed files — these are where complexity lives",
    "- Any file with complex business logic that isn't explained in existing context",
    "",
    "**Project configuration** — deployment and infrastructure context:",
    "- `Dockerfile`, `docker-compose.yml` — services, ports, dependencies",
    "- `.github/workflows/`, `.gitlab-ci.yml`, `Jenkinsfile` — CI/CD pipeline",
    "- `.env.example`, `.env.template` — required environment variables",
    "- `Makefile`, `justfile`, `Taskfile` — developer workflows",
    "",
    "### Phase 3: Ask the developer about what code can't reveal",
    "",
    "Ask targeted questions based on gaps you found. These should be specific, not generic:",
    "",
    "**Good questions** (based on actually reading code):",
    "- \"I see complex retry logic in `src/queue/worker.ts` — what should a new developer know about the queue system?\"",
    "- \"CLAUDE.md says 'Express API' but I see GraphQL resolvers in `src/graphql/` — should the architecture section mention this?\"",
    "- \"The key types list includes `UserService` but that file was deleted 5 commits ago. Can I remove it?\"",
    "- \"I see 3 different error handling patterns across the codebase — is there a preferred approach?\"",
    "- \"What are the gotchas when setting up the dev environment for the first time?\"",
    "- \"Are there any areas of the code that are fragile or have known issues?\"",
    "",
    "**Bad questions** (too generic, could be asked about any repo):",
    "- \"What does this project do?\" (read the README)",
    "- \"What testing framework do you use?\" (static analysis already knows)",
    "",
    "Present questions conversationally. Wait for the developer's answers.",
    "",
    "### Phase 4: Populate context into the right files",
    "",
    "Based on everything you've learned:",
    "1. Save developer answers to `.claude/.onboard-answers.json` (add to `domainQA` array, set `answeredAt`)",
    "2. Run `npx claude-onboard update` to regenerate auto-sections",
    "3. For context that requires manual edits, edit files directly — but ONLY outside the auto-markers",
    "",
    "**Where different context goes** — use your judgement based on scope:",
    "- **Folder-scoped** (module-specific patterns, gotchas, internal conventions) → `<dir>/CLAUDE.md` outside auto-markers. Prefer this for anything a developer working in that folder needs to know.",
    "- **Project-wide** (cross-cutting architecture, global conventions, overall patterns) → `.claude/context/` files. Enrich existing files or create new topic files as needed.",
    "- **Developer answers** → `.claude/.onboard-answers.json`",
    "- **Everything else** → manual sections of `.claude/CLAUDE.md` (outside auto-markers)",
    "",
    "### Folder-Level CLAUDE.md — Verify and Enrich",
    "",
    "Each hotpath directory has its own `CLAUDE.md` with auto-generated key types and hot files. The auto-generated content is a skeleton — your job is to add the context that static analysis can't provide.",
    "",
    "For each folder-level CLAUDE.md:",
    "1. **Read** the auto-generated content (inside the auto-markers)",
    "2. **Read** the actual source files in that directory — understand what the module does",
    "3. **Verify** the key types are still accurate and descriptions are meaningful (not just \"service\" or \"Spring component\")",
    "4. **Ask the developer** about this module if the purpose isn't clear from code alone:",
    "   - \"What business problem does the `core/` module solve?\"",
    "   - \"How does `persistence/` relate to `core/`? Are there any ORM gotchas?\"",
    "   - \"Are there ordering constraints or hidden dependencies between these modules?\"",
    "5. **Add context outside the auto-markers** with what you learned:",
    "   - Module purpose and business domain it serves",
    "   - How this module relates to other modules (dependencies, data flow)",
    "   - Non-obvious patterns or conventions specific to this directory",
    "   - Known gotchas, fragile areas, or things that break easily",
    "",
    "Example of enriched folder CLAUDE.md:",
    "```markdown",
    "<!-- Manual context added by developer/agent -->",
    "## Purpose",
    "Handles order allocation to field executives. The AllocationEngine is the core abstraction —",
    "subclasses implement different strategies (standard, batch, future serviceability).",
    "",
    "## Key Relationships",
    "- Depends on `persistence/` for FE availability data",
    "- Called by `web/` controllers via use-case interfaces in `core/domain/`",
    "",
    "## Gotchas",
    "- AllocationEngine subclasses must be @Service beans — the strategy pattern relies on Spring injection",
    "- ProspectiveFieldExecutive is mutable during allocation — don't cache across requests",
    "",
    "<!-- onboarder:auto-start -->",
    "(auto-generated content)",
    "<!-- onboarder:auto-end -->",
    "```",
    "",
    "## Auto-Marker System",
    "",
    "Files use markers to separate auto-generated and manual content:",
    "```",
    "<!-- onboarder:auto-start -->",
    "(auto-generated content — will be overwritten on regeneration)",
    "<!-- onboarder:auto-end -->",
    "```",
    "Content OUTSIDE these markers is preserved during regeneration. Content INSIDE is replaced.",
    "",
    "## Managed Files",
    "",
    "**Auto-marker files** (auto section regenerated, manual sections preserved):",
    "- `.claude/CLAUDE.md` — main project context",
  );

  if (sa && sa.hotpathDirs.length > 0) {
    for (const dir of sa.hotpathDirs) {
      sections.push(`- \`${dir}/CLAUDE.md\` — folder-level context`);
    }
  }

  sections.push(
    "",
    "**Write-once files** (never overwritten after creation unless forced):",
    "- `.claude/context/architecture.md`",
    "- `.claude/context/patterns.md`",
    "- `.claude/context/hotfiles.md`",
    "- `.claude/commands/*.md` — all command files",
    "- `.claude/agents/*.md` — all agent files (outside auto-markers)",
    "",
    "**Agent-created files** (created by context-maintainer as needed during git history mining):",
    "- `.claude/context/*.md` — additional topic files (e.g., `decisions.md`, `tech-debt.md`, `contributor-map.md`)",
    "- These are maintained across update cycles — read them in Phase 1, update them in Phase 2",
    "",
    "**Data files** (always overwritten):",
    "- `.claude/.onboard-snapshot.json`",
    "- `.claude/.onboarder-meta.json`",
    "",
    "## Staleness Detection",
    "",
    "To determine if context needs updating:",
    "1. Read `.claude/.onboarder-meta.json` to get `lastUpdated` timestamp",
    "2. Run `git log --oneline --since=\"<lastUpdated>\"` to count commits since last update",
    "3. Context is **stale** if any of these are true:",
    "   - More than 20 commits since last update",
    "   - New directories exist under `src/` that don't have folder-level CLAUDE.md files",
    "   - `package.json` (or equivalent build file) has changed since last update",
    "   - New frameworks or major dependencies were added",
    "",
    "## Context Quality Verification",
    "",
    "After extracting and populating context, verify completeness across 8 dimensions (each scored 0-5):",
    "",
    "| Dimension | 5 (Excellent) | 3 (Adequate) | 1 (Poor) | 0 (Missing) |",
    "|-|-|-|-|-|",
    "| **Project Identity** | Clear purpose, audience, and scope | Purpose stated but vague | Generic fallback description | No description |",
    "| **Build & Run** | All commands verified correct | Commands listed but unverified | Some commands, missing key ones | No commands |",
    "| **Architecture** | Modules, layers, entry points match code | High-level structure documented | Vague or partially wrong | Not documented |",
    "| **Key Types** | Important types with accurate descriptions | Types listed, descriptions generic | Types listed but stale/wrong | Not documented |",
    "| **Conventions** | Commit, naming, test conventions accurate | Some conventions documented | Conventions listed but wrong | Not documented |",
    "| **Framework Decisions** | Project-specific choices documented | Some choices noted | Generic framework info (not useful) | Not documented |",
    "| **Domain Context** | Business logic, gotchas, tribal knowledge | Some domain notes | Superficial domain info | Not documented |",
    "| **Staleness** | All sections reflect current code | Minor drift in 1-2 sections | Multiple stale sections | Docs mostly outdated |",
    "",
    "**Overall score**: Sum of all dimensions × 2.5 = 0-100",
    "",
    "Write your evaluation to `.claude/.onboard-score.json`:",
    "```json",
    "{",
    "  \"evaluatedAt\": \"<ISO timestamp>\",",
    "  \"evaluatedBy\": \"context-maintainer-agent\",",
    "  \"overall\": 72,",
    "  \"rubric\": {",
    "    \"projectIdentity\": { \"score\": 4, \"max\": 5, \"notes\": \"Clear description from README\" },",
    "    \"buildAndRun\": { \"score\": 3, \"max\": 5, \"notes\": \"Missing lint command\" },",
    "    \"architecture\": { \"score\": 4, \"max\": 5, \"notes\": \"Layers documented correctly\" },",
    "    \"keyTypes\": { \"score\": 3, \"max\": 5, \"notes\": \"2 types removed since last update\" },",
    "    \"conventions\": { \"score\": 4, \"max\": 5, \"notes\": \"Commit convention accurate\" },",
    "    \"frameworkDecisions\": { \"score\": 2, \"max\": 5, \"notes\": \"No project-specific React choices\" },",
    "    \"domainContext\": { \"score\": 2, \"max\": 5, \"notes\": \"No business logic documented\" },",
    "    \"staleness\": { \"score\": 4, \"max\": 5, \"notes\": \"Minor drift in hotfiles\" }",
    "  },",
    "  \"gaps\": [",
    "    { \"dimension\": \"frameworkDecisions\", \"issue\": \"Uses React but no state management choice documented\" },",
    "    { \"dimension\": \"domainContext\", \"issue\": \"src/billing/ has complex logic not explained anywhere\" }",
    "  ]",
    "}",
    "```",
    "",
    "Repeat the extract → populate → verify loop until score ≥ 80 or max 5 rounds.",
    "",
    "## Writing Style",
    "",
    "- Be concise. Claude reads these files at the start of every conversation — every line costs context.",
    "- Focus on WHAT and WHY, not HOW. Claude can read the code for implementation details.",
    "- Prioritize information Claude can't easily grep for: architectural decisions, domain concepts, non-obvious conventions.",
    "- Never duplicate information that's already in the auto-generated sections.",
  );

  return agentFrontmatter({
    name: "context-maintainer",
    description: "Senior-developer onboarding agent. Extracts context from code, git history, and developer knowledge, then populates it into the right files. Spawn after init or update.",
    tools: ["Read", "Write", "Edit", "Glob", "Grep", "Bash"],
    model: "sonnet",
    memory: "project",
    maxTurns: 25,
  }) + agentBody(sections);
}

export function renderSecurityAuditorAgent(analysis: RepositoryAnalysis): string {
  const sa = analysis.sourceAnalysis;
  const arch = analysis.architecture;
  const sections: string[] = [
    `# Security Auditor — ${analysis.repoName}`,
    "",
    "You audit this repository for security vulnerabilities specific to its tech stack.",
    "",
    "## Tech Stack",
    "",
    `- **Language**: ${analysis.primaryLanguage}`,
    `- **Frameworks**: ${analysis.frameworks.join(", ") || "None detected"}`,
  ];

  // Dependencies by group
  if (sa) {
    const depGroups = groupBy(sa.dependencies, (d) => d.group);
    if (depGroups.size > 0) {
      sections.push("", "## Dependencies by Category", "");
      for (const [group, deps] of depGroups) {
        if (group === "other" || group === "code-gen" || group === "logging") continue;
        const names = deps.map((d) => d.name.split(":").pop()!).slice(0, 8).join(", ");
        sections.push(`- **${group}**: ${names}`);
      }
    }
  }

  // Database patterns
  if (arch.databasePatterns.length > 0) {
    sections.push("", "## Database Patterns", "");
    for (const p of arch.databasePatterns) {
      sections.push(`- ${p}`);
    }
  }

  // API patterns
  if (arch.apiPatterns.length > 0) {
    sections.push("", "## API Patterns", "");
    for (const p of arch.apiPatterns) {
      sections.push(`- ${p}`);
    }
  }

  // Entry points
  if (arch.entryPoints.length > 0) {
    sections.push("", "## Entry Points", "");
    for (const ep of arch.entryPoints) {
      sections.push(`- \`${ep}\``);
    }
  }

  // Framework-specific audit guidance
  const frameworks = analysis.frameworks.map((f) => f.toLowerCase());
  const hasSpring = frameworks.some((f) => f.includes("spring"));
  const hasDjango = frameworks.some((f) => f.includes("django"));
  const hasExpress = frameworks.some((f) => f.includes("express"));
  const hasNextjs = frameworks.some((f) => f.includes("next"));
  const hasFastAPI = frameworks.some((f) => f.includes("fastapi"));

  sections.push(
    "",
    "## Audit Process",
    "",
    "### Step 1: Map the attack surface",
    "Use `Grep` to find all entry points:",
  );

  if (hasSpring) {
    sections.push(
      "- `@RequestMapping`, `@GetMapping`, `@PostMapping`, `@PutMapping`, `@DeleteMapping` — REST endpoints",
      "- `@Controller`, `@RestController` — controller classes",
      "- `@Scheduled` — scheduled tasks (can they be triggered externally?)",
      "- `@EventListener` — event handlers",
    );
  } else if (hasExpress) {
    sections.push(
      "- `app.get`, `app.post`, `app.put`, `app.delete`, `router.get`, etc. — route handlers",
      "- `app.use` — middleware registration",
    );
  } else if (hasDjango) {
    sections.push(
      "- `urls.py` / `path()` / `re_path()` — URL routing",
      "- `views.py` — view functions/classes",
      "- `@api_view` / `ViewSet` — DRF endpoints",
    );
  } else if (hasFastAPI) {
    sections.push(
      "- `@app.get`, `@app.post`, `@router.get`, etc. — route handlers",
      "- `Depends()` — dependency injection (check auth dependencies)",
    );
  } else if (hasNextjs) {
    sections.push(
      "- `app/api/` or `pages/api/` — API routes",
      "- `middleware.ts` — edge middleware",
      "- Server actions (`'use server'`)",
    );
  } else {
    sections.push(
      `- Search for route/endpoint definitions common in ${analysis.primaryLanguage} web frameworks`,
    );
  }

  sections.push(
    "",
    "### Step 2: Authentication & Authorization",
  );

  if (hasSpring) {
    sections.push(
      "- Check `SecurityFilterChain` / `WebSecurityConfigurerAdapter` — which endpoints are public vs protected?",
      "- Search for `@PreAuthorize`, `@Secured`, `@RolesAllowed` — are role checks applied consistently?",
      "- Check OAuth2/JWT config: is token validation properly configured? Are scopes enforced?",
      "- **Actuator exposure**: search for `management.endpoints.web.exposure` — are `/actuator/env`, `/actuator/heapdump` exposed?",
      "- Check CORS config: `@CrossOrigin` or `CorsConfigurationSource` — is it overly permissive (`allowedOrigins(\"*\")`)?",
      "- CSRF: is CSRF disabled? If so, is it justified (stateless API with JWT)?",
    );
  } else if (hasExpress) {
    sections.push(
      "- Check middleware chain: is auth middleware applied before route handlers?",
      "- Search for `passport`, `jwt`, `express-session` — how is auth implemented?",
      "- CORS: check `cors()` config — is it overly permissive?",
      "- Rate limiting: is `express-rate-limit` or equivalent applied?",
    );
  } else if (hasDjango) {
    sections.push(
      "- Check `MIDDLEWARE` in settings.py — is auth middleware present?",
      "- Search for `@login_required`, `@permission_required`, `IsAuthenticated`",
      "- CSRF: is `CsrfViewMiddleware` enabled? Any `@csrf_exempt` decorators?",
    );
  } else {
    sections.push(
      "- Verify all endpoints have authentication checks",
      "- Check for authorization (role/permission) enforcement",
      "- Look for endpoints accidentally left public",
    );
  }

  sections.push(
    "",
    "### Step 3: Injection vulnerabilities",
  );

  if (hasSpring || analysis.primaryLanguage === "Java") {
    sections.push(
      "- **HQL/JPQL injection**: search for string concatenation in `@Query` annotations or `createQuery()` calls. Safe: `@Query(\"... WHERE x = :param\")`. Unsafe: `\"... WHERE x = \" + input`",
      "- **Native SQL injection**: search for `nativeQuery = true` — these bypass JPA parameterization",
      "- **SpEL injection**: search for `@Value(\"#{...}\")`, `@PreAuthorize` with user input in expressions",
      "- **LDAP injection**: if LDAP is used, check for unescaped DN construction",
      "- **Log injection**: search for user input directly in log statements without sanitization",
    );
  } else if (analysis.primaryLanguage === "Python") {
    sections.push(
      "- **SQL injection**: search for f-strings or `.format()` in SQL queries. Safe: parameterized queries. Unsafe: `f\"SELECT * FROM x WHERE id = {user_input}\"`",
      "- **Template injection**: search for `render_template_string` with user input (Jinja2 SSTI)",
      "- **Command injection**: search for `os.system`, `subprocess.call` with `shell=True`",
    );
  } else if (analysis.primaryLanguage === "TypeScript" || analysis.primaryLanguage === "JavaScript") {
    sections.push(
      "- **SQL injection**: search for template literals in SQL queries. Safe: parameterized queries (`$1`, `?`). Unsafe: `` `SELECT * FROM x WHERE id = ${input}` ``",
      "- **XSS**: search for `dangerouslySetInnerHTML`, `innerHTML`, `document.write` with user input",
      "- **Command injection**: search for `child_process.exec` with string concatenation",
      "- **Prototype pollution**: search for deep merge/extend utilities with user-controlled input",
    );
  } else {
    sections.push(
      "- Check for string interpolation/concatenation in database queries",
      "- Check for command execution with user input",
      "- Check for template rendering with user input",
    );
  }

  sections.push(
    "",
    "### Step 4: Secrets & configuration",
    "- `Grep` for hardcoded credentials: `password`, `secret`, `api_key`, `token`, `private_key` in source files (not config templates)",
    "- Check `.gitignore` — are `.env`, credential files, and key files excluded?",
    "- Check if secrets are loaded from environment variables or a secrets manager vs hardcoded",
    "",
    "### Step 5: Data exposure",
    "- Check error handlers: do they return stack traces or internal details to clients?",
    "- Check logging: is sensitive data (passwords, tokens, PII) being logged?",
    "- Check API responses: are internal fields (database IDs, internal status) leaking to clients?",
    "",
    "## Output Format",
    "",
    "Structure your audit report as:",
    "```",
    "## Security Audit — [repo name]",
    "",
    "### Attack Surface",
    "- N endpoints found (N public, N authenticated)",
    "",
    "### Findings",
    "",
    "#### [CRITICAL|HIGH|MEDIUM|LOW] Finding title",
    "- **File**: `path/to/file.ext:line`",
    "- **Category**: Injection | Auth | Secrets | Data Exposure | Config",
    "- **Issue**: Description of the vulnerability",
    "- **Impact**: What an attacker could do",
    "- **Fix**: Specific code change or approach",
    "",
    "### Summary",
    "- Critical: N, High: N, Medium: N, Low: N",
    "- Most urgent fix: [description]",
    "```",
  );

  return agentFrontmatter({
    name: "security-auditor",
    description: "Security auditor specialized in this repo's tech stack vulnerabilities",
    tools: ["Read", "Glob", "Grep", "Bash"],
    model: "sonnet",
    permissionMode: "plan",
    maxTurns: 25,
  }) + agentBody(sections);
}
